In [5]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving ecommerce_master_10000.csv.xlsx to ecommerce_master_10000.csv (1).xlsx

In [23]:
category_analysis = (
    df_analysis
    .groupby("Main_category")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Units_sold=("Total_quantity", "sum"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_revenue", ascending=False)
)

display(category_analysis)

,Total_orders,Units_sold,Total_revenue,Average_order_value
Main_category,,,,
Electronics,2261,6683,55182459.45,24406.22
Sports & Fitness,1186,3082,7560370.72,6374.68
Home & Kitchen,976,2576,4796590.84,4914.54
Fashion,1161,2784,4320042.67,3720.97
Beauty & Personal Care,1694,3418,2741448.15,1618.33
Toys & Games,1002,2270,2627288.68,2622.04
Books,1003,1807,930579.51,927.80
Grocery,717,1211,560498.27,781.73

In [ ]:
brand_analysis = (
    df_analysis
    .groupby("Main_brand")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Units_sold=("Total_quantity", "sum"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_revenue", ascending=False)
)

display(brand_analysis.head(10))

            Total_orders  Units_sold  Total_revenue  Average_order_value
Main_brand
Kratos              1451        4088    26114188.24             17997.37
Aurelia             1050        2627    12799134.59             12189.65
UrbanEdge           1249        2898     8788044.59              7036.06
Maple                900        2237     8150052.87              9055.61
Bloom               1216        2811     5811481.75              4779.18
Zenix                874        2065     5402686.99              6181.56
Vega                1185        2501     4001268.82              3376.60
PureLeaf             757        1763     3506144.24              4631.63
Orbit                595        1196     2293752.81              3855.05
Nova                 723        1645     1852523.39              2562.27

In [7]:
import pandas as pd

df = pd.read_excel(
    list(uploaded.keys())[0],
    sheet_name="ecommerce_master_10000"
)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (10000, 34)

,Order_id,Customer_id,Order_date,Device,Payment_method,Order_status,Shipping_cost,Discount_pct,Coupon_used,Delivery_days,...,Order_month,Search_interest_index,Avg_competitor_price,Market_growth_pct,Industry_ad_spend_cr,Order_ID_Check,Calculated_Net_Amount,Net_Amount_Check,Age_Group,Column1
0,1,1251,2025-09-16,Mobile,Credit Card,Cancelled,99,0,0,1,...,2025-09,76.6,1210.19,2.18,1.51,1.0,3973.32,True,25-34,0.0
1,2,79,2026-04-07,Desktop,Debit Card,Returned,0,5,1,3,...,2026-04,76.0,1181.97,1.72,2.36,NaN,861.02,True,25-34,0.0
2,3,196,2026-01-22,Mobile,Net Banking,Delivered,0,0,0,4,...,2026-01,83.4,1247.02,2.85,1.68,NaN,4480.67,True,25-34,NaN
3,4,112,2025-02-22,Desktop,UPI,Delivered,40,25,1,2,...,2025-02,63.6,1753.31,1.37,2.23,NaN,3602.40,True,35-44,NaN
4,5,1887,2026-01-12,Mobile,COD,Returned,60,15,1,3,...,2026-01,69.6,11320.57,3.33,4.63,NaN,30719.93,True,25-34,NaN

In [25]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

Number of rows: 10000
Number of columns: 34

Column names:
['Order_id', 'Customer_id', 'Order_date', 'Device', 'Payment_method', 'Order_status', 'Shipping_cost', 'Discount_pct', 'Coupon_used', 'Delivery_days', 'Gender', 'Age', 'City', 'State', 'Customer_signup_date', 'Acquisition_channel', 'Loyalty_tier', 'Num_items', 'Total_quantity', 'Gross_amount', 'Total_cost', 'Main_category', 'Main_brand', 'Net_amount', 'Order_month', 'Search_interest_index', 'Avg_competitor_price', 'Market_growth_pct', 'Industry_ad_spend_cr', 'Order_ID_Check', 'Calculated_Net_Amount', 'Net_Amount_Check', 'Age_Group', 'Column1']

In [8]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Dataset shape: (10000, 34)

Column names:
['Order_id', 'Customer_id', 'Order_date', 'Device', 'Payment_method', 'Order_status', 'Shipping_cost', 'Discount_pct', 'Coupon_used', 'Delivery_days', 'Gender', 'Age', 'City', 'State', 'Customer_signup_date', 'Acquisition_channel', 'Loyalty_tier', 'Num_items', 'Total_quantity', 'Gross_amount', 'Total_cost', 'Main_category', 'Main_brand', 'Net_amount', 'Order_month', 'Search_interest_index', 'Avg_competitor_price', 'Market_growth_pct', 'Industry_ad_spend_cr', 'Order_ID_Check', 'Calculated_Net_Amount', 'Net_Amount_Check', 'Age_Group', 'Column1']

Data types:
Order_id                          int64
Customer_id                       int64
Order_date               datetime64[ns]
Device                           object
Payment_method                   object
Order_status                     object
Shipping_cost                     int64
Discount_pct                      int64
Coupon_used                       int64
Delivery_days                     int64
Gender                           object
Age                               int64
City                             object
State                            object
Customer_signup_date     datetime64[ns]
Acquisition_channel              object
Loyalty_tier                     object
Num_items                         int64
Total_quantity                    int64
Gross_amount                    float64
Total_cost                      float64
Main_category                    object
Main_brand                       object
Net_amount                      float64
Order_month                      object
Search_interest_index           float64
Avg_competitor_price            float64
Market_growth_pct               float64
Industry_ad_spend_cr            float64
Order_ID_Check                  float64
Calculated_Net_Amount           float64
Net_Amount_Check                   bool
Age_Group                        object
Column1                         float64
dtype: object

In [13]:
# Check missing values in each column
print("Missing values:")
print(df.isnull().sum())

# Check completely duplicated rows
print("\nDuplicate rows:", df.duplicated().sum())

# Check duplicate order IDs
print("Duplicate Order IDs:", df["Order_id"].duplicated().sum())

Missing values:
Order_id                    0
Customer_id                 0
Order_date                  0
Device                      0
Payment_method              0
Order_status                0
Shipping_cost               0
Discount_pct                0
Coupon_used                 0
Delivery_days               0
Gender                      0
Age                         0
City                        0
State                       0
Customer_signup_date        0
Acquisition_channel         0
Loyalty_tier                0
Num_items                   0
Total_quantity              0
Gross_amount                0
Total_cost                  0
Main_category               0
Main_brand                  0
Net_amount                  0
Order_month                 0
Search_interest_index       0
Avg_competitor_price        0
Market_growth_pct           0
Industry_ad_spend_cr        0
Order_ID_Check           9999
Calculated_Net_Amount       0
Net_Amount_Check            0
Age_Group                   0
Column1                  9997
dtype: int64

Duplicate rows: 0
Duplicate Order IDs: 0

In [14]:
df_analysis = df.drop(
    columns=[
        "Order_ID_Check",
        "Calculated_Net_Amount",
        "Net_Amount_Check",
        "Column1"
    ]
)

print("Original shape:", df.shape)
print("Analysis shape:", df_analysis.shape)
print(df_analysis.columns.tolist())

Original shape: (10000, 34)
Analysis shape: (10000, 30)
['Order_id', 'Customer_id', 'Order_date', 'Device', 'Payment_method', 'Order_status', 'Shipping_cost', 'Discount_pct', 'Coupon_used', 'Delivery_days', 'Gender', 'Age', 'City', 'State', 'Customer_signup_date', 'Acquisition_channel', 'Loyalty_tier', 'Num_items', 'Total_quantity', 'Gross_amount', 'Total_cost', 'Main_category', 'Main_brand', 'Net_amount', 'Order_month', 'Search_interest_index', 'Avg_competitor_price', 'Market_growth_pct', 'Industry_ad_spend_cr', 'Age_Group']

In [15]:
import pandas as pd
import numpy as np

# Work with the analysis copy created earlier
print("Dataset shape:", df_analysis.shape)
print("Total orders:", df_analysis["Order_id"].nunique())
print("Duplicate rows:", df_analysis.duplicated().sum())
print("Duplicate order IDs:", df_analysis["Order_id"].duplicated().sum())

# Missing values
print("\nMissing values:")
print(df_analysis.isnull().sum())

# Data types
print("\nData types:")
print(df_analysis.dtypes)

Dataset shape: (10000, 30)
Total orders: 10000
Duplicate rows: 0
Duplicate order IDs: 0

Missing values:
Order_id                 0
Customer_id              0
Order_date               0
Device                   0
Payment_method           0
Order_status             0
Shipping_cost            0
Discount_pct             0
Coupon_used              0
Delivery_days            0
Gender                   0
Age                      0
City                     0
State                    0
Customer_signup_date     0
Acquisition_channel      0
Loyalty_tier             0
Num_items                0
Total_quantity           0
Gross_amount             0
Total_cost               0
Main_category            0
Main_brand               0
Net_amount               0
Order_month              0
Search_interest_index    0
Avg_competitor_price     0
Market_growth_pct        0
Industry_ad_spend_cr     0
Age_Group                0
dtype: int64

Data types:
Order_id                          int64
Customer_id                       int64
Order_date               datetime64[ns]
Device                           object
Payment_method                   object
Order_status                     object
Shipping_cost                     int64
Discount_pct                      int64
Coupon_used                       int64
Delivery_days                     int64
Gender                           object
Age                               int64
City                             object
State                            object
Customer_signup_date     datetime64[ns]
Acquisition_channel              object
Loyalty_tier                     object
Num_items                         int64
Total_quantity                    int64
Gross_amount                    float64
Total_cost                      float64
Main_category                    object
Main_brand                       object
Net_amount                      float64
Order_month                      object
Search_interest_index           float64
Avg_competitor_price            float64
Market_growth_pct               float64
Industry_ad_spend_cr            float64
Age_Group                        object
dtype: object

In [16]:

df_analysis = df_analysis.copy()

text_cols = df_analysis.select_dtypes(include="object").columns

for col in text_cols:
    df_analysis[col] = df_analysis[col].str.strip()


df_analysis["Order_date"] = pd.to_datetime(
    df_analysis["Order_date"], errors="coerce"
)

df_analysis["Customer_signup_date"] = pd.to_datetime(
    df_analysis["Customer_signup_date"], errors="coerce"
)


print("Invalid order dates:", df_analysis["Order_date"].isna().sum())
print("Invalid signup dates:", df_analysis["Customer_signup_date"].isna().sum())

print("\nNumeric summary:")
display(df_analysis.describe().round(2))

Invalid order dates: 0
Invalid signup dates: 0

Numeric summary:

,Order_id,Customer_id,Order_date,Shipping_cost,Discount_pct,Coupon_used,Delivery_days,Age,Customer_signup_date,Num_items,Total_quantity,Gross_amount,Total_cost,Net_amount,Search_interest_index,Avg_competitor_price,Market_growth_pct,Industry_ad_spend_cr
count,10000.00,10000.00,10000,10000.00,10000.00,10000.00,10000.00,10000.00,10000,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,5000.50,1002.68,2025-10-31 00:31:06.240000256,40.34,5.34,0.30,3.51,32.35,2025-04-08 07:58:48,1.90,2.38,8271.35,5489.61,7871.93,73.53,3213.86,1.46,3.17
min,1.00,1.00,2024-01-03 00:00:00,0.00,0.00,0.00,1.00,18.00,2024-01-01 00:00:00,1.00,1.00,76.04,42.80,57.03,33.50,271.17,-2.89,0.55
25%,2500.75,510.00,2025-05-21 00:00:00,0.00,0.00,0.00,2.00,25.00,2024-08-15 00:00:00,1.00,1.00,878.00,577.24,878.27,60.70,669.03,0.17,1.98
50%,5000.50,995.00,2025-12-03 00:00:00,40.00,0.00,0.00,3.00,32.00,2025-03-19 00:00:00,2.00,2.00,2937.75,1886.25,2798.23,71.80,1183.05,1.38,3.02
75%,7500.25,1525.00,2026-05-12 00:00:00,60.00,10.00,1.00,5.00,39.00,2025-12-08 00:00:00,2.00,3.00,8300.36,5356.19,7954.24,87.80,2023.75,2.67,4.38
max,10000.00,2000.00,2026-09-30 00:00:00,99.00,25.00,1.00,10.00,63.00,2026-08-30 00:00:00,5.00,11.00,175294.62,112707.15,175393.62,100.00,11958.37,6.58,7.97
std,2886.90,577.90,NaN,37.60,8.31,0.46,1.54,9.15,NaN,1.12,1.59,14443.90,9546.40,13744.99,17.03,4089.78,1.70,1.57

In [17]:
# Overall business metrics
revenue_summary = pd.DataFrame({
    "Metric": [
        "Total Orders",
        "Total Net Amount",
        "Average Order Value",
        "Total Quantity Sold",
        "Average Discount (%)",
        "Average Delivery Days"
    ],
    "Value": [
        df_analysis["Order_id"].nunique(),
        df_analysis["Net_amount"].sum(),
        df_analysis["Net_amount"].mean(),
        df_analysis["Total_quantity"].sum(),
        df_analysis["Discount_pct"].mean(),
        df_analysis["Delivery_days"].mean()
    ]
})

display(revenue_summary.round(2))

                  Metric        Value
0           Total Orders     10000.00
1       Total Net Amount  78719278.29
2    Average Order Value      7871.93
3    Total Quantity Sold     23831.00
4   Average Discount (%)         5.34
5  Average Delivery Days         3.51

In [18]:
monthly_revenue = (
    df_analysis
    .groupby("Order_month")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_index()
)

display(monthly_revenue)

print("Highest revenue month:")
display(monthly_revenue.nlargest(1, "Total_revenue"))

print("Lowest revenue month:")
display(monthly_revenue.nsmallest(1, "Total_revenue"))

             Total_orders  Total_revenue  Average_order_value
Order_month
2024-01                16      109258.51              6828.66
2024-02                15      109933.19              7328.88
2024-03                49      619663.31             12646.19
2024-04                28      332242.08             11865.79
2024-05                67      537390.56              8020.75
2024-06                74      874525.16             11817.91
2024-07                75      563731.97              7516.43
2024-08               135      882158.72              6534.51
2024-09               132     1050245.40              7956.40
2024-10               268     1907193.75              7116.39
2024-11               240     1898278.65              7909.49
2024-12               231     1824144.67              7896.73
2025-01               215     1703198.18              7921.85
2025-02               238     2110319.66              8866.89
2025-03               247     2085495.49              8443.30
2025-04               210     1670666.40              7955.55
2025-05               363     3024843.44              8332.90
2025-06               229     1574613.87              6876.04
2025-07               289     2406133.68              8325.72
2025-08               403     2978389.67              7390.55
2025-09               375     2980169.19              7947.12
2025-10               501     4063612.58              8111.00
2025-11               553     3641331.74              6584.69
2025-12               531     4225259.09              7957.17
2026-01               494     3473048.77              7030.46
2026-02               374     3231868.81              8641.36
2026-03               440     3222888.47              7324.75
2026-04               456     3885510.69              8520.86
2026-05               639     4499336.75              7041.22
2026-06               496     3771208.43              7603.24
2026-07               558     4873969.39              8734.71
2026-08               711     5995860.81              8433.00
2026-09               348     2592787.21              7450.54

Highest revenue month:

             Total_orders  Total_revenue  Average_order_value
Order_month
2026-08               711     5995860.81               8433.0

Lowest revenue month:

             Total_orders  Total_revenue  Average_order_value
Order_month
2024-01                16      109258.51              6828.66

In [19]:
market_analysis = (
    df_analysis
    .groupby("Order_month")
    .agg(
        Total_revenue=("Net_amount", "sum"),
        Average_search_interest=("Search_interest_index", "mean"),
        Average_market_growth=("Market_growth_pct", "mean"),
        Average_ad_spend=("Industry_ad_spend_cr", "mean"),
        Average_competitor_price=("Avg_competitor_price", "mean")
    )
    .round(2)
    .sort_index()
)

display(market_analysis)

,Total_revenue,Average_search_interest,Average_market_growth,Average_ad_spend,Average_competitor_price
Order_month,,,,,
2024-01,109258.51,62.77,2.11,3.07,3323.62
2024-02,109933.19,44.65,0.89,3.33,3654.14
2024-03,619663.31,48.97,0.28,2.18,5167.57
2024-04,332242.08,50.11,0.37,2.80,3694.21
2024-05,537390.56,54.23,0.23,2.75,2900.63
2024-06,874525.16,51.39,1.33,2.96,3701.13
2024-07,563731.97,56.54,0.87,2.78,2902.71
2024-08,882158.72,67.41,1.39,3.15,3449.05
2024-09,1050245.40,64.92,2.28,2.61,3021.83
2024-10,1907193.75,95.65,2.57,4.43,3424.07
2024-11,1898278.65,92.43,3.62,5.80,2991.26
2024-12,1824144.67,77.90,0.97,3.17,3100.73
2025-01,1703198.18,72.66,1.04,3.30,3162.82
2025-02,2110319.66,54.08,0.96,2.78,3127.25
2025-03,2085495.49,53.54,0.90,2.48,3227.25
2025-04,1670666.40,55.15,1.14,2.92,3162.02
2025-05,3024843.44,62.67,0.80,2.59,3460.53
2025-06,1574613.87,55.21,0.83,2.49,2816.12
2025-07,2406133.68,61.09,1.39,3.03,3228.22
2025-08,2978389.67,76.31,1.99,2.50,3208.92
2025-09,2980169.19,72.43,1.49,3.08,3118.62
2025-10,4063612.58,97.83,4.71,5.18,3204.06
2025-11,3641331.74,97.29,2.62,4.47,2840.85
2025-12,4225259.09,86.71,0.54,2.16,3304.10
2026-01,3473048.77,76.89,2.13,2.97,3074.63
2026-02,3231868.81,60.77,1.49,2.74,3954.41
2026-03,3222888.47,63.23,1.41,3.23,3114.11
2026-04,3885510.69,64.06,1.44,3.14,3162.34
2026-05,4499336.75,68.61,0.79,3.20,3074.79
2026-06,3771208.43,62.16,1.07,2.36,3253.03
2026-07,4873969.39,71.68,0.55,3.20,3205.62
2026-08,5995860.81,87.35,0.33,2.99,3371.84
2026-09,2592787.21,77.64,0.96,2.52,3116.19

In [20]:
average_net_amount = df_analysis["Net_amount"].mean()

high_value_orders = (
    df_analysis[df_analysis["Net_amount"] > average_net_amount]
    [
        ["Order_id", "Customer_id", "Order_date",
         "Main_category", "Net_amount"]
    ]
    .sort_values("Net_amount", ascending=False)
)

display(high_value_orders.head(20))

      Order_id  Customer_id Order_date Main_category  Net_amount
9723      9724          169 2026-09-07   Electronics   175393.62
5743      5744          202 2025-12-14   Electronics   170759.96
8373      8374         1456 2026-05-08   Electronics   149005.62
283        284         1590 2024-11-26   Electronics   148040.57
5559      5560         1134 2025-09-22   Electronics   145985.51
662        663         1622 2024-04-19   Electronics   145328.57
5485      5486           41 2025-09-16   Electronics   140048.94
3175      3176         1079 2026-04-07   Electronics   136476.80
347        348         1682 2025-09-03   Electronics   134905.04
8527      8528         1934 2026-07-30   Electronics   134692.43
31          32          705 2024-11-02   Electronics   133343.42
8268      8269          158 2026-04-27   Electronics   129090.61
5735      5736          294 2025-10-06   Electronics   126939.00
3844      3845         1754 2025-03-12   Electronics   124635.89
930        931         1745 2024-06-09   Electronics   123860.62
8362      8363          813 2026-08-16   Electronics   117650.74
7956      7957          580 2026-03-24   Electronics   117295.75
3932      3933         1448 2025-03-28   Electronics   112804.37
4349      4350         1846 2025-05-12   Electronics   112744.37
4859      4860          948 2025-07-17   Electronics   112498.58

In [21]:
monthly_growth = monthly_revenue.copy()

monthly_growth["Previous_Month_Revenue"] = (
    monthly_growth["Total_revenue"].shift(1)
)

monthly_growth["Growth_Percentage"] = (
    (
        monthly_growth["Total_revenue"]
        - monthly_growth["Previous_Month_Revenue"]
    )
    / monthly_growth["Previous_Month_Revenue"].replace(0, np.nan)
    * 100
).round(2)

display(monthly_growth)

,Total_orders,Total_revenue,Average_order_value,Previous_Month_Revenue,Growth_Percentage
Order_month,,,,,
2024-01,16,109258.51,6828.66,NaN,NaN
2024-02,15,109933.19,7328.88,109258.51,0.62
2024-03,49,619663.31,12646.19,109933.19,463.67
2024-04,28,332242.08,11865.79,619663.31,-46.38
2024-05,67,537390.56,8020.75,332242.08,61.75
2024-06,74,874525.16,11817.91,537390.56,62.74
2024-07,75,563731.97,7516.43,874525.16,-35.54
2024-08,135,882158.72,6534.51,563731.97,56.49
2024-09,132,1050245.40,7956.40,882158.72,19.05
2024-10,268,1907193.75,7116.39,1050245.40,81.60
2024-11,240,1898278.65,7909.49,1907193.75,-0.47
2024-12,231,1824144.67,7896.73,1898278.65,-3.91
2025-01,215,1703198.18,7921.85,1824144.67,-6.63
2025-02,238,2110319.66,8866.89,1703198.18,23.90
2025-03,247,2085495.49,8443.30,2110319.66,-1.18
2025-04,210,1670666.40,7955.55,2085495.49,-19.89
2025-05,363,3024843.44,8332.90,1670666.40,81.06
2025-06,229,1574613.87,6876.04,3024843.44,-47.94
2025-07,289,2406133.68,8325.72,1574613.87,52.81
2025-08,403,2978389.67,7390.55,2406133.68,23.78
2025-09,375,2980169.19,7947.12,2978389.67,0.06
2025-10,501,4063612.58,8111.00,2980169.19,36.36
2025-11,553,3641331.74,6584.69,4063612.58,-10.39
2025-12,531,4225259.09,7957.17,3641331.74,16.04
2026-01,494,3473048.77,7030.46,4225259.09,-17.80
2026-02,374,3231868.81,8641.36,3473048.77,-6.94
2026-03,440,3222888.47,7324.75,3231868.81,-0.28
2026-04,456,3885510.69,8520.86,3222888.47,20.56
2026-05,639,4499336.75,7041.22,3885510.69,15.80
2026-06,496,3771208.43,7603.24,4499336.75,-16.18
2026-07,558,4873969.39,8734.71,3771208.43,29.24
2026-08,711,5995860.81,8433.00,4873969.39,23.02
2026-09,348,2592787.21,7450.54,5995860.81,-56.76

In [26]:
category_ranking = category_analysis.copy()

category_ranking["Revenue_Rank"] = (
    category_ranking["Total_revenue"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

display(category_ranking.sort_values("Revenue_Rank"))

,Total_orders,Units_sold,Total_revenue,Average_order_value,Revenue_Rank
Main_category,,,,,
Electronics,2261,6683,55182459.45,24406.22,1
Sports & Fitness,1186,3082,7560370.72,6374.68,2
Home & Kitchen,976,2576,4796590.84,4914.54,3
Fashion,1161,2784,4320042.67,3720.97,4
Beauty & Personal Care,1694,3418,2741448.15,1618.33,5
Toys & Games,1002,2270,2627288.68,2622.04,6
Books,1003,1807,930579.51,927.80,7
Grocery,717,1211,560498.27,781.73,8

In [27]:
state_analysis = (
    df_analysis
    .groupby("State")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_revenue", ascending=False)
)

display(state_analysis.head(10))

               Total_orders  Total_revenue  Average_order_value
State
Maharashtra            2286    17414858.64              7618.05
Tamil Nadu             1998    15714046.86              7864.89
Delhi                  1370    10554931.30              7704.33
Karnataka              1144     8923953.83              7800.66
Telangana               798     6189299.93              7756.01
West Bengal             763     6036206.80              7911.15
Kerala                  483     4215932.55              8728.64
Rajasthan               370     3367644.47              9101.74
Gujarat                 418     3256810.44              7791.41
Uttar Pradesh           370     3045593.47              8231.33

In [28]:
delivery_analysis = (
    df_analysis
    .groupby("Order_status")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Average_delivery_days=("Delivery_days", "mean"),
        Median_delivery_days=("Delivery_days", "median")
    )
    .round(2)
)

display(delivery_analysis)

              Total_orders  Average_delivery_days  Median_delivery_days
Order_status
Cancelled              734                   3.51                   3.0
Delivered             8360                   3.52                   3.0
Returned               728                   3.46                   3.0
Shipped                178                   3.30                   3.0

In [29]:
coupon_analysis = (
    df_analysis
    .groupby("Coupon_used")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Average_discount=("Discount_pct", "mean"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
)

display(coupon_analysis)

,Total_orders,Average_discount,Total_revenue,Average_order_value
Coupon_used,,,,
0,7014,1.22,57715680.69,8228.64
1,2986,15.02,21003597.60,7034.02

In [30]:
df_analysis["Discount_Group"] = pd.cut(
    df_analysis["Discount_pct"],
    bins=[-np.inf, 0, 10, 20, np.inf],
    labels=["No Discount", "Low Discount", "Medium Discount", "High Discount"],
    include_lowest=True
)

discount_analysis = (
    df_analysis
    .groupby("Discount_Group", observed=False)
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
)

display(discount_analysis)

                 Total_orders  Total_revenue  Average_order_value
Discount_Group
No Discount              6440    53413110.28              8293.96
Low Discount             1401    10676112.02              7620.35
Medium Discount          1477    10615762.84              7187.38
High Discount             682     4014293.15              5886.06

In [31]:
status_analysis = (
    df_analysis
    .groupby("Order_status")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Recorded_net_amount=("Net_amount", "sum")
    )
)

status_analysis["Order_percentage"] = (
    status_analysis["Total_orders"]
    / status_analysis["Total_orders"].sum()
    * 100
).round(2)

display(status_analysis.round(2))

cancelled = (df_analysis["Order_status"] == "Cancelled").sum()
returned = (df_analysis["Order_status"] == "Returned").sum()
total_orders = df_analysis["Order_id"].nunique()

print("Cancellation rate (%):", round(cancelled / total_orders * 100, 2))
print("Return rate (%):", round(returned / total_orders * 100, 2))

              Total_orders  Recorded_net_amount  Order_percentage
Order_status
Cancelled              734           5788154.85              7.34
Delivered             8360          65882585.02             83.60
Returned               728           5719324.88              7.28
Shipped                178           1329213.54              1.78

Cancellation rate (%): 7.34
Return rate (%): 7.28

In [32]:
device_analysis = (
    df_analysis
    .groupby("Device")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_orders", ascending=False)
)

display(device_analysis)

         Total_orders  Total_revenue  Average_order_value
Device
Mobile           6438    50272804.43              7808.76
Desktop          3032    24298307.65              8013.95
Tablet            530     4148166.21              7826.73

In [33]:
payment_analysis = (
    df_analysis
    .groupby("Payment_method")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum")
    )
    .round(2)
)

payment_analysis["Order_percentage"] = (
    payment_analysis["Total_orders"]
    / payment_analysis["Total_orders"].sum()
    * 100
).round(2)

display(payment_analysis.sort_values("Total_orders", ascending=False))

                Total_orders  Total_revenue  Order_percentage
Payment_method
UPI                     3811    29883729.90             38.11
Credit Card             1802    13864183.00             18.02
COD                     1667    13520371.18             16.67
Debit Card              1418    11058367.41             14.18
Net Banking              704     5640362.30              7.04
Wallet                   598     4752264.50              5.98

In [34]:
acquisition_analysis = (
    df_analysis
    .groupby("Acquisition_channel")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_revenue", ascending=False)
)

display(acquisition_analysis)

                     Total_orders  Total_revenue  Average_order_value
Acquisition_channel
Organic Search               2296    18286409.18              7964.46
Social Media                 2333    17672605.35              7575.06
Paid Ads                     2043    16170732.14              7915.19
Direct                       1396    10705452.81              7668.66
Email                         953     8205356.49              8610.03
Referral                      979     7678722.32              7843.43

In [35]:
loyalty_analysis = (
    df_analysis
    .groupby("Loyalty_tier")
    .agg(
        Total_orders=("Order_id", "nunique"),
        Total_revenue=("Net_amount", "sum"),
        Average_order_value=("Net_amount", "mean")
    )
    .round(2)
    .sort_values("Total_revenue", ascending=False)
)

display(loyalty_analysis)

              Total_orders  Total_revenue  Average_order_value
Loyalty_tier
Gold                  2588    29845924.96             11532.43
Silver                3184    23348198.44              7332.98
Platinum              1864    19133784.44             10264.91
Bronze                2364     6391370.45              2703.63